/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <iostream>
#include <opencv2/opencv.hpp>
#include <vector>
#include <android/log.h>
/* Header for class com_honeybilly_opencvdemo_utils_LocalProcesser */

#define  LOG_TAG    "MYHAARDETECTION"

#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)
#define  LOGW(...)  __android_log_print(ANDROID_LOG_WARN,LOG_TAG,__VA_ARGS__)
#define  LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG,__VA_ARGS__)
#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)

#ifndef _Included_com_honeybilly_opencvdemo_utils_LocalProcesser
#define _Included_com_honeybilly_opencvdemo_utils_LocalProcesser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_honeybilly_opencvdemo_utils_LocalProcesser
 * Method:    faceDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_honeybilly_opencvdemo_utils_LocalProcesser_faceDetection
  (JNIEnv* env, jobject, jlong addrRgba);

/*
 * Class:     com_honeybilly_opencvdemo_utils_LocalProcesser
 * Method:    initLoad
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jboolean JNICALL Java_com_honeybilly_opencvdemo_utils_LocalProcesser_initLoad
  (JNIEnv* env, jobject, jstring haarfilePath);

#ifdef __cplusplus
}
#endif
#endif

void scaleIntervalSampling(const cv::Mat &src, cv::Mat &dst, double xRatio, double yRatio);
